# 环境配置
environment:
  city: "Chicago"  # 城市名称

# EPR模型参数
epr_model:
  rho: 0.6      # 探索新位置的倾向
  gamma: 0.21   # 探索意愿随访问地点数量的衰减系数
  beta: 0.8     # 等待时间分布的幂律指数
  alpha: 0.55   # 距离分布的幂律指数
  max_steps: 1000

simulation:
  total_steps: 50  # 总步数

# LLM配置
llm:
  model_name: "Pro/Qwen/Qwen2.5-7B-Instruct"
  platform: "siliconflow"
  api_key: 'sk-zuayonhuqaoiyyjxuueihsxwpuyoayehanxderyrokorhppb'
  temperature: 0.7
